/* Generated by wayland-scanner 1.18.0 */

/*
 * TODO choose license, probably MIT
 */

#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif


static const struct wl_interface *hwbuf_types[] = {
	NULL,
	NULL,
	NULL,
};

static const struct wl_message hwbuf_manager_requests[] = {
	{ "destroy", "", hwbuf_types + 0 },
	{ "set_socket", "h", hwbuf_types + 0 },
	{ "create_buffer", "uusun", hwbuf_types + 0 },
};

static const struct wl_message hwbuf_manager_events[] = {
	{ "socket_received", "", hwbuf_types + 0 },
};

WL_PRIVATE const struct wl_interface hwbuf_manager_interface = {
	"hwbuf_manager", 1,
	3, hwbuf_manager_requests,
	1, hwbuf_manager_events,
};

